### ISSUE TITLE
transfer domain out of Dave's name

### ISSUE THREAD

**Issue by sglyon** [NYUDataBootcamp/website#3]

**Comment by sglyon** [comment]
@cc7768 will you talk to Stan about doing this today? I can send him an email, but if he has questions I think it would be best for you to be there

We need to transfer it to the email address nyu.databootcamp@gmail.com

**Comment by sglyon** [comment]
I think we can follow these instructions: https://support.google.com/domains/answer/6260895?hl=en

**Comment by sglyon** [comment]
I can actually start the process on my end. I think we will just need to be able to get a code from Dave's email address. It will probably be easiest to sit down at the same time and take care of it at once.

**Comment by cc7768** [comment]
We no longer need to do this -- We will now use `data-bootcamp.com`
