### ISSUE TITLE
Something besides google groups?

### ISSUE THREAD

**Issue by cc7768** [NYUDataBootcamp/website#4]
Should we switch to a different group management tool (such as [discourse](http://www.discourse.org/))?

**Comment by sglyon** [comment]
I would love to, I wonder how much of a headache it would be to set it up?

**Comment by cc7768** [comment]
Seems to be relatively easy through AWS -- Downside is that it would be (at least) $25/month.

https://bitnami.com/stack/discourse/cloud/aws

**Comment by sglyon** [comment]
Other options:
- https://www.discoursehosting.com/pricing/
- https://www.digitalocean.com/products/one-click-apps/discourse/?utm_source=google&utm_medium=NB_SEM&utm_campaign=Topic_Tier2_discourse&utm_content=custom&utm_term=%2Bdiscourse%20%2Bhosting&gclid=CLmnxYWjxM4CFeQK0wodOIALOQ

Whatever we do I think we pay for it -- probably not worth it

**Comment by sglyon** [comment]
not happening right now.
